### PR TITLE
allow defaults in LabrelledPetriNet(ODESystem)

### PR DESCRIPTION
**Pull request by anandijain**

### CODE REVIEW

**Review by mehalter — APPROVED** [review]
This looks great, once the tests pass I'll get this merged in. Thank you!

**Comment by mehalter** [comment]
@anandijain just a heads up I added a commit here to resolve the github actions issues

**Comment by anandijain** [comment]
thanks, can we tag?

**Comment by mehalter** [comment]
I'm waiting on one more PR to get a reply from before tagging the next release. In the mean time you can checkout the master branch in your julia session if you want to use it.

**Pull request merged**
