### PR TITLE
Expanded Conversion from BilayerNetwork to PetriNet

### PR DESCRIPTION
**Pull request by bosonbaas**
This PR addresses the problem that there are bilayer networks which do not trivially convert to an equivalent Petri net through functorial data migration. One such example is the following bilayer equivalent to the SIR Petri net model.
image

The `balance!` function adds or removes pairs of Wn, Wa wires in order to allow for functorial data migration.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
@cl4yton and I talked about this problem when we first added BilayerNetworks. This is another example of how you need to undo simplifications before you can operate on a term. I think this is the right strategy, namely, add back the edges that are implied by the assumption that the bilayer network came from mass action kinetics and then migrate.

**Comment by bosonbaas** [comment]
Exactly. This PR also exposes the fact that there are certain Bilayer networks which cannot be expressed by mass-action on a Petri net, and throws an error if the conversion is not possible.

**Review by mehalter — APPROVED** [review]
LGTM

**Pull request merged**
