### PR TITLE
Add Stratification API

### PR DESCRIPTION
**Pull request by mehalter**
Building an API surrounding automatic stratification (across demographic categories and spatial separation) of a given Petri model.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
Is this going to get merged here or did it get taken care of in the ASKE WG repo?

**Comment by mehalter** [comment]
It got taken care of with the ASKE repo, but Andrew and I are using this branch/draft PR to pass notes and share code for now and the PR interface provides and easy way to quickly see changes over time as opposed to the GH straight commit browser

**Pull request closed without merging**
