### PR TITLE
Do not canonicalize `+` and `-` during ODESystem conversion

### PR DESCRIPTION
**Pull request by YingboMa**
PR:
```julia
julia> ModelingToolkit.equations(model_odesys)
2-element Vector{Equation}:
 Differential(t)(A1(t)) ~ (2A1_A1*(A1(t)^2) + A1_A2*A1(t)*A2(t) + A2_A1*A1(t)*A2(t)) - (2A1_A1*(A1(t)^2) + A1_A2*A1(t)*A2(t) + A2_A1*A1(t)*A2(t))
 Differential(t)(A2(t)) ~ (2A2_A2*(A2(t)^2) + A1_A2*A1(t)*A2(t) + A2_A1*A1(t)*A2(t)) - (2A2_A2*(A2(t)^2) + A1_A2*A1(t)*A2(t) + A2_A1*A1(t)*A2(t))
```

Master:
```julia
julia> ModelingToolkit.equations(ODESystem(model_bilayer))
2-element Vector{Equation}:
 Differential(t)(A1(t)) ~ 0
 Differential(t)(A2(t)) ~ 0
```

### CODE REVIEW

**Comment by jpfairbanks** [comment]
Can you add a comment note that tells you how to get the old behavior? I think that simplifying the equations is good. But I understand why you want this (based on a slack thread with Nelson).

**Comment by YingboMa** [comment]
@jpfairbanks ready for review.

**Comment by jpfairbanks** [comment]
Changes look good except the tests failing. I can't see the test log on my phone. But once tests pass, LGTM

**Comment by mehalter** [comment]
re-running the code coverage test, shouldn't be a problem with this PR. I'll get this merged this morning oncce I get that one to run. Looks like it's a classic github action issue

**Review by mehalter — APPROVED** [review]
LGTM!

**Comment by liunelson** [comment]
@mehalter When will you have your next release so we can use this fix in our work?

**Comment by mehalter** [comment]
> @mehalter When will you have your next release so we can use this fix in our work?

I can tag a new release tomorrow morning. Until then, you can use Julia to check out and use the `master` branch to test and use this fix in your work

**Pull request merged**
