### PR TITLE
Update to use struct acsets

### PR DESCRIPTION
**Pull request by tylerhanks**
Updated to be compatible with catlab struct acsets. A couple things to note:

1. I had to change the signatures of `Open(p::AbstractReactionNet{R,C})` and `Open(p::AbstractLabelledReactionNet{R,C})` to just `Open(p::ReactionNet{R,C})` and `Open(p::LabelledReactionNet{R,C})` because I don't think the new abstract acset types have any notion of being parameterized by types (they are not created from a schema). The disadvantage of this is you can no longer pass custom subtypes of rxn nets to `Open`. I'm assuming there's a way to re-generalize this code under the new system but I haven't figured it out yet so any input would be appreciated.
2. Sort of in the same vein as 1, I changed `function petri_homomorphisms(p1::T, p2::T; kw...) where {CD, AD, T <: AbstractACSet{CD,AD}}` to just `function petri_homomorphisms(p1::AbstractPetriNet, p2::AbstractPetriNet; kw...)` for the same reason as above. This works but we lose the compile-time checking that p1 and p2 are instances of the same schema. Again, I'm assuming there's probably a way to add this back in if we want.

Also, this is my first ever pr to anything larger than a small group project so go easy on me 😄

### CODE REVIEW

**Comment by bosonbaas** [comment]
Thanks for the work done on this, this looks great! I unfortunately won't be able to get around to taking a closer look at this until later this week, but I'm looking forward to getting this integration with the new ACSet structure working!

**Comment by bosonbaas** [comment]
I think one problem we're going to run into will be that `Petri.jl` doesn't yet have support for Catlab 0.13, so the tests won't be able to find a satisfactory version of Catlab.
@mehalter what do you think about making a major release after we merge this PR, which both adds support for Catlab 0.13 and removes any dependencies on Petri.jl? I've published an issue about migrating Petri functionality over at #72.

**Comment by bosonbaas** [comment]
It looks like it'll be a little more involved of a task to remove support for Petri.jl, so we'll just be updating Petri.jl and keeping #72 alive.
@tylerhanks would you be able to update the compat entry in the Project.toml file? If you change it from
```julia
Catlab = "0.12.7"
```
to 
```julia
Catlab = "0.13"
```
then the tests should run with the new Catlab. They'll still fail until we update Petri.jl, but they'll be all ready to pass once Petr is updated!

**Comment by tylerhanks** [comment]
@bosonbaas done

**Comment by bosonbaas** [comment]
Great, looks like tests are passing! Now the only thing that will need to be updated is the documentation in the `examples` folder. Currently it looks like the examples are using some features from the old ACSets, and so the docs are breaking.

I see from the CI docs results that one of the errors is in `examples/covid/chime/chime-cset.jl`. There, the line
```
JSON.print(sir_cset_string.tables, 2)
```
should be able to be replaced with the `generate_json_acset` function [here](https://github.com/AlgebraicJulia/Catlab.jl/blob/master/src/categorical_algebra/CSets.jl)

@tylerhanks if you're up for fixing the documentation code, I'll leave it in your capable hands, but I'm also happy to take a crack at it.

**Comment by tylerhanks** [comment]
Sorry for the late response @bosonbaas , I was sick last week. I'm down to take a stab at it tho if you haven't already.

**Comment by bosonbaas** [comment]
Hope you're feeling better! I haven't touched it yet, so you can have at it.

**Comment by bosonbaas** [comment]
I was taking a look at this documentation, and found a pretty hairy error that was actually originating in the Catlab source! I'll push some of my edits, which hopefully helps with the docs
https://github.com/AlgebraicJulia/Catlab.jl/issues/520

**Comment by tylerhanks** [comment]
@bosonbaas sweet, no problem! Sorry I didn't get around to doing the documentation; I was totally swamped this week with school.

**Pull request merged**
