### PR TITLE
more efficient vectorfield

### PR DESCRIPTION
**Pull request by slwu89**
Takes over for #101, defines a new method `vectorfield_expr` as suggested by @jpfairbanks that will return a function which calculates the vectorfield according to the `f!(du, u, p, t)` signature. It is a bit faster than the version based on transition matrices on the enzyme_reactions.jl example.

I'm marking this as a draft because I'd like some help with the method; currently it has a world age problem due to calling `eval` on the expr before returing, meaning that it only works if called from the global scope. The commented out test in bilayednetworks.jl will not work because it is being called from function scope, but I'm not sure whats the best way to modify the function to work from any calling scope.

### CODE REVIEW

**Comment by slwu89** [comment]
Please note the tests are failing due to an update in Catalyst, see other PR #106

**Comment by mehalter** [comment]
Now that the catalyst stuff has been fixed on master @slwu89 could we Rebase this PR and see if the tests pass? :)

**Comment by slwu89** [comment]
Thanks @mehalter, yeah I'll rebase! I'm interested though to see if anyone with more experience dealing with world-age issues related to `eval` can help me figure out a way to get `vectorfield_expr` to work from any calling scope, since it's a bit annoying that right now it will only work if called from global scope.

**Comment by epatters** [comment]
World-age issues are annoying and I've never understood very well how world age actually works, but in the past I've had mixed success using [GeneralizedGenerated.jl](https://github.com/JuliaStaging/GeneralizedGenerated.jl) to work around them.

**Comment by slwu89** [comment]
Thanks for the ~~black magic~~ helpful advice @epatters, that does indeed bypass the world age issue and the test checking that the returned vectorfield is working from within a function scope is passing!

Also added the [macos gitignore items](https://github.com/github/gitignore/blob/main/Global/macOS.gitignore) to .gitignore, some mac junk snuck into my commit.

**Comment by epatters** [comment]
It is indeed black magic, but I'm glad it worked!

**Review by mehalter — APPROVED** [review]
This looks great, thanks for looking into this @slwu89 !

**Pull request merged**
