### PR TITLE
Fix bad assumption in `oapply_typed`

### LINKED ISSUE #155: oapply_typed results in wrong wiring
This simple SEIR example gives a wiring from I to R in the UWD (correct) but from E to R in the labelled Petri net.

```julia
using AlgebraicPetri,AlgebraicPetri.TypedPetri
using Catlab, Catlab.CategoricalAlgebra, Catlab.Programs
using Catlab.WiringDiagrams, Catlab.Graphics
using AlgebraicDynamics.UWDDynam


epi_transitions = LabelledPetriNet(
  [:Pop],
  :infection=>((:Pop, :Pop)=>(:Pop, :Pop)),
  :progression=>(:Pop=>:Pop),
  :recovery=>(:Pop=>:Pop)
)

seir_uwd = @relation () where (S::Pop, E::Pop, I::Pop, R::Pop) begin
    infection(S, I, E, I)
    progression(E, I)
    recovery(I, R)
end
to_graphviz(seir_uwd, box_labels=:name, junction_labels=:variable)

seir_acst = oapply_typed(epi_transitions, seir_uwd, [:β, :δ, :γ])
seir_lpn = dom(seir_acst)
Graph(seir_lpn)
```

@jpfairbanks found that changing the order to `(S::Pop, I::Pop, E::Pop, R::Pop)` in the `@relation` fixed this.

### PR DESCRIPTION
**Pull request by epatters**
Resolves #155. Note that the fix requires exposing the junctions in the UWD through outer ports, hence is also a breaking change. See the changes to the unit tests.

### CODE REVIEW

**Comment by epatters** [comment]
@mehalter, what do you think about the breaking aspect of this PR? To avoid a breaking change, we could modify the outer ports of the supplied UWD if they do not conform to the required. This would be slightly inelegant but not too bad.

**Comment by mehalter** [comment]
@epatters thanks for looking into this! Yeah I agree it's a bit unfortunate for this to be a breaking change. I think for now it's a good idea to put in something slightly inelegant to avoid breaking things with a `TODO` comment indicating which code is a bit hacky and should be removed in the next breaking release. What do you think?

**Comment by epatters** [comment]
OK, fixed! This should be ready to go now.

**Review by mehalter — APPROVED** [review]
Awesome! Thanks so much!

**Pull request merged**
