### PR TITLE
Vectorfield without constructing TransitionMatrices

### LINKED ISSUE #77: Inefficiency in `vectorfield` function
The `vectorfield` function currently iterates through each element of the transition matrix, making each evaluation be O(ST) for number of states S and number of transitions T. This can cause significant slowdown on large sparse PetriNets, and could be improved by using a sparse representation of the transition matrix.

### PR DESCRIPTION
**Pull request by slwu89**
Addresses #77 by constructing the vectorfield function by reading the required information off the ACSet directly.

Resolves #77

### CODE REVIEW

**Comment by mehalter** [comment]
I did a quick rebase to get this up to date with the current master

**Review by mehalter — APPROVED** [review]
Looks great! Just waiting for tests to pass :D

**Comment by slwu89** [comment]
Must be some weird hiccup on whatever machine is running the CI, since I did check that the docs built on my machine before submitting the PR.

**Comment by mehalter** [comment]
Yeah I don't think it's erroring out according to the action logs, but it's just hanging. I'm not sure what to do because I want to bump the version after this and tag a new release with this improvement and the Open Transitions and we need the docs to rebuild and deploy with the new version so they stay current with the version drop down 🤔

**Comment by slwu89** [comment]
Yeah, I'm not sure. Maybe cancel and re-run the workflow?

**Comment by mehalter** [comment]
@epatters I have seen it fail two times so far, I can confirm I can build them locally and @slwu89 has confirmed as well. I saw something like this last week as well and I tried the next day and it worked 🤷🏼

**Comment by epatters** [comment]
OK, thanks. Good 'ol GitHub CI, always so reliable...

**Comment by slwu89** [comment]
Seems like every time the documentation CI hangs, it is on the enzyme_reaction.ipynb file, but I don't know why. Just (re)confirmed that everything is building locally.

**Comment by jpfairbanks** [comment]
Thanks Sean, this is a nice cleanup feature that will improve maintainability.

**Comment by mehalter** [comment]
Started a docs build on the current master just to see how it goes: https://github.com/AlgebraicJulia/AlgebraicPetri.jl/actions/runs/4074665962/jobs/7108266116

**Comment by slwu89** [comment]
@mehalter I'm thinking we should close this PR. Based on the convo with @jpfairbanks on zulip, I decided to just implement a version that builds the whole function as an expression, which should be the fastest without diving into symbolic stuff. It's here on another branch on my fork: https://github.com/slwu89/AlgebraicPetri.jl/blob/slwu89/vf-expr/src/AlgebraicPetri.jl#L289

Coming back to this however I discovered this strange error #105 which we'll need to figure out before proceeding with anything. Thanks!

**Pull request closed without merging**
