### PR TITLE
Conversion Tooling to Catalyst

### PR DESCRIPTION
**Pull request by bosonbaas**
This PR provides tooling for converting from PetriNets to the Catalyst ReactionSystem object.

This allows us to take advantage of the Catalyst parameter estimation tooling once the petrinet is constructed.

### CODE REVIEW

**Comment by bosonbaas** [comment]
Currently the Julia 1.0 tests are failing because Catalyst only supports Julia 1.3 and up. I was hoping to keep the Julia 1.0 tests since we're using Requires.jl for Catalyst.
I'm able to restrict whether Catalyst is actually imported in the tests by checking the VERSION value while running, but is there a way to make Catalyst a conditional dependency for the test suite (so that we don't get a package unsatisfiability error in Julia 1.0)?

**Comment by jpfairbanks** [comment]
I don't see anything about this in the Pkg docs. Probably worth raising an issue over it.

**Comment by bosonbaas** [comment]
I realized now that I should be able to fix the fact that Catalyst support should only be tested for `VERSION >= v1.3` if I include a separate Project.toml file for the v1.0 tests. Is this a valid solution, or is this too hacky? I would probably just put this in `test/v1.0/Project.toml` and modify the current CI workflow to look there for the v1.0 tests.

**Comment by epatters** [comment]
Micah might feel differently, but if it were me, I'd just make the minimum version be Julia v1.3. I feel like regardless of the official LTS status, the community is basically giving up on v1.0 at this point.

**Comment by bosonbaas** [comment]
Just because I think it'd be a shame to lose 1.0 support for something that isn't even a dependency, I went ahead and modified the CI so that the 1.0 test looks for it's test dependencies in `test/v1.0`.
If this is too hacky, I can definitely change it back and just up the minimum supported version to 1.3.

**Review by mehalter — APPROVED** [review]
LGTM

**Pull request merged**
